#!/bin/bash

# if [[ $SSHPASS == "" ]]; then
# 	cat "Error: environment variable SSHPASS not set!" 0>&2
# 	exit
# fi

for ip in 152 228 229 235 18 22 36 39 42; do
	ping -c1 -W5 "172.16.200.$ip"
	if [[ $? == 0 ]]; then
		basename="proxmox-172.16.200.$ip"
		if [[ ! -d "$basename" ]]
		then
			mkdir -p "$basename/etc/network"
			mkdir -p "$basename/etc/pve"
		fi

		if [[ ! -d "global" ]]
		then
			mkdir -p "global"
		fi

		scp "/etc/hosts" "$basename/etc"
		scp "/etc/network/interfaces" "$basename/network/"
		scp "/etc/resolv.conf" "$basename/etc/"
		scp -r "/etc/pve/qemu-server"* "$basename/etc/"
		scp -r "/etc/pve/lxc"* "$basename/etc/"

		for file in $(find /etc/pve -maxdepth 1 | cut -d'/' -f4)
		do
			if [[ ! -d "/etc/pve/nodes/$HOSTNAME/$file" && "$file" != "nodes" ]]
			then
				scp -r "/etc/pve/$file" "global/"
			fi
		done
	fi
done
